feat: add basic router
Suficks/eCommerce pull request #21
Opened 2024-05-11 15:00 UTC by samael-god

#### Issue

Add basic router: [RSS-ECOMM-2_08](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint2/RSS-ECOMM-2_08.md), [RSS-ECOMM-2_16](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint2/RSS-ECOMM-2_16.md), [RSS-ECOMM-2_21](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint2/RSS-ECOMM-2_21.md).

#### 🤔 This is a ...

- [x] 🌟 New feature
- [ ] ⚙️ Update feature
- [ ] 🔧 Fix feature
- [ ] 🐛 Refactor code
- [ ] 🔗 Fix a broken link
- [ ] ✏️ Fix a typo or grammatical error
- [ ] ❓ Other (specify: **\*\*\*\***\_\_\_\_**\*\*\*\***)

#### Description

- **Brief Overview:**Basic routing implementation. Different approach for unauthorized and authorized is **not implemented**.

#### Additional Information

- **Screenshots/Links:**

#### Checklist

- [x] ✅ I have performed a self-review of my own code.
- [ ] 📝 I have commented my code, particularly in hard-to-understand areas.
- [ ] 🔧 I have made corresponding changes to the documentation (if applicable).
- [x] 🚫 My changes generate no new warnings or errors.

2024-05-12 11:05 UTC, neemkashu requested changes
не разбрасывайте логику роутера в несколько файлов, неудобное

как минимум сделайте один конфиг
как максимум перейдите на createBrowserRouter

судя по тому, что всё роуты обёрнуты в саспенс, у вас планы на загрузку данных через роутер. тогда опять же будет проще делать делать через более декларативный createBrowserRouter

2024-05-12 11:05 UTC, neemkashu commented on src/app/providers/Router/Config/routeConfig.tsx
> +  },
я бы насовала компонентов "заглушек" с каким-нибудь хедером с текстом, зависящим от страницы, а то как убедиться, что всё работает
но это опциально

2024-05-12 11:05 UTC, neemkashu commented on src/app/providers/ui/AppRouter.tsx
> +    return <Route path={route.path} element={element} key={route.path} />;
деструктуризацию роута реквестирую

const { path, element } = route
const component = <Suspense>{element}</Suspense>

2024-05-12 11:05 UTC, neemkashu commented on src/app/providers/ui/AppRouter.tsx
> +    </Routes>
почему юзаем старое апи??
<img width="400" alt="image" src="https://github.com/Suficks/eCommerce/assets/111371378/cd6c49af-bb3a-43bd-8e72-ea2127c20dde">


более простой в использовании: https://reactrouter.com/en/main/routers/create-browser-router
скорее всего он сам оборачивает в Route твои компоненты из конфига

тогда настройки роутера не будут разбросана по нескольким файлам

2024-05-12 11:05 UTC, neemkashu commented on src/shared/const/router.ts
> +export const getRouteCategory = (category: string) => `/catalog${category}`;
возможно, тут не хватает слеша до category

2024-05-12 11:05 UTC, neemkashu commented on src/shared/const/router.ts
> +export const getRouteMain = () => '/main';
не вижу особого смысла вытаскивать эти настройки из конфига для роутера и именовать отдельно
пусть лежат в routerConfig

ксттати, я не понимаю, почему они должны быть функциями? если ради динамических роутов, то даю ссылку в другом комменте, как их делать

2024-05-12 11:05 UTC, neemkashu commented on src/shared/const/router.ts
> +export const getRouteCategory = (category: string) => `/catalog${category}`;
динамические роуты делаются, наприме, так
https://reactrouter.com/en/main/route/route#dynamic-segments

2024-05-13 08:45 UTC, Suficks approved these changes

2024-05-13 08:50 UTC, merged