Feat/commercetools api
Suficks/eCommerce pull request #34
Opened 2024-05-17 09:15 UTC by Suficks

#### Issue

Change CommerceTools Api 

#### 🤔 This is a ...

- [x] 🌟 New feature
- [ ] ⚙️ Update feature
- [x] 🔧 Fix feature
- [ ] 🐛 Refactor code
- [ ] 🔗 Fix a broken link
- [ ] ✏️ Fix a typo or grammatical error
- [ ] ❓ Other (specify: **\*\*\*\***\_\_\_\_**\*\*\*\***)

#### Description

- **Brief Overview:** This PR change commerceTools Api and requests. Also add wrapper to main page

#### Additional Information

- **Screenshots/Links:**

#### Checklist

- [x] ✅ I have performed a self-review of my own code.
- [ ] 📝 I have commented my code, particularly in hard-to-understand areas.
- [ ] 🔧 I have made corresponding changes to the documentation (if applicable).
- [x] 🚫 My changes generate no new warnings or errors.

2024-05-18 14:19 UTC, neemkashu requested changes
Отлично! у меня есть замечания, но самые важные из них про строки и магические числа

2024-05-18 14:19 UTC, neemkashu commented on src/features/Login/model/services/loginThunk.ts
> +      return rejectWithValue(ValidationErrors.serverError.error);
хороший тон брать ошибки апи за `unknown` и обрабатывать, узнав тип
```
    } catch (error: unknown) {
      if (error instanceof Error) {
        const { message } = error;
        if (message === 'emailError') {
          return rejectWithValue(ValidationErrors.email.notExist);
        }
        if (message === 'passwordError') {
          return rejectWithValue(ValidationErrors.password.wrongPassword);
        }
      }

      return rejectWithValue(ValidationErrors.serverError.error);
    }
```

2024-05-18 14:19 UTC, neemkashu commented on src/features/Login/model/services/loginThunk.ts
> +      return rejectWithValue(ValidationErrors.serverError.error);
ещё надо понимать, что юзеру мы никогда не показыаем, он ошибся в логине или пароле, но для учебного проекта норм

2024-05-18 14:19 UTC, neemkashu commented on src/features/Login/model/slice/loginSlice.ts
>          // state.error = action.payload;
закомменченный код убираем, кстати action должен бвть линтер подсветить как неиспользованный

2024-05-18 14:19 UTC, neemkashu commented on src/features/Login/ui/LoginForm.tsx
>      }
кмк лезть в мету в каждом месте, где ты делаешь запросы к апи будет странно. смотри, что предлагают в доке
https://redux-toolkit.js.org/api/createAsyncThunk#handling-thunk-results

```
import { unwrapResult } from '@reduxjs/toolkit'

// in the component
const onClick = async () => {
  try {
    const resultAction = await dispatch(fetchUserById(userId))
    const originalPromiseResult = unwrapResult(resultAction)
    // handle result here
  } catch (rejectedValueOrSerializedError) {
    // handle error here
  }
}
```

2024-05-18 14:19 UTC, neemkashu commented on src/features/Registration/model/services/signUpUser.ts
> +        }
то же замечание, что в комменте к логину

2024-05-18 14:19 UTC, neemkashu commented on src/features/Registration/model/services/signUpUser.ts
> +    const { email, alreadyExist, serverError, password } = ValidationErrors;
припиши суффикс  `as const` в месте объявления этого объекта

2024-05-18 14:19 UTC, neemkashu commented on src/features/Registration/model/services/signUpUser.ts
> +        case 'The provided value is not a valid email': {
откуда весь этот список кейсов? если это серверные ошибки, у них обычно есть код и именно по нему нужно кейситься. если это фиксированный список сообщений, то надо вынести в константу as const или енам

2024-05-18 14:19 UTC, neemkashu commented on src/pages/MainPage/MainPage.tsx
> +        <img src={HeaderImage} alt="headerImage" className={cls.headerImage} />
лучше альт из пустой строки, чем какой-то джава скрипт код. это скорее всего декоративная картинка, к таким пушут пустой альт

2024-05-18 14:19 UTC, neemkashu commented on src/pages/MainPage/MainPage.tsx
> +            alt="background"
нужен  альт из пустой строки

2024-05-18 14:19 UTC, neemkashu commented on src/pages/MainPage/MainPage.tsx
> +                }}
затем делать кнопку вместо ссылки? так что тут тоже NavLink, пожалуйста. можно его декорировать похожим на кнопку, но кнопки хуже ссылок по UX (user experience) и доступности

2024-05-18 14:19 UTC, neemkashu commented on src/pages/MainPage/MainPage.tsx
> +                <img src={Icon_insta} alt="icon" />
альт из пустой строки к любым иконкам, если в ссылке есть текст.
если тескта нет, то нужно дать человеческое название для ссылки в альт

2024-05-18 14:19 UTC, neemkashu commented on src/shared/api/BuildClient.ts
> +export let apirootPassword: ByProjectKeyRequestBuilder | null = null;
кажется, игнор линтера и этот экспорт устарели. apirootPassword в приложении используется через constructClientPasswordFlow

const apirootPassword = constructClientPasswordFlow(email, password);

2024-05-18 14:19 UTC, neemkashu commented on src/shared/api/BuildClient.ts
я в этом файле ничего не понимаю. работает -- хорошо ))

2024-05-18 14:19 UTC, neemkashu commented on src/shared/api/requests/loginUser.ts
> +      activeCartSignInMode: 'MergeWithExistingCustomerCart',
magic string
создать переменную с именем

2024-05-18 14:19 UTC, neemkashu commented on src/shared/api/requests/loginUser.ts
> +    localStorage.setItem('token', tokenInstance.get().token);
все имена, по которым что-то кладётся в LS, положите в  енам в shared. возможны коллизии, да и искать где что лежит будет неудобно

2024-05-18 14:19 UTC, neemkashu commented on src/shared/api/requests/loginUser.ts
> +          cause: 'emailError',
вот эти вот строковые кейсы должны лежать в каком-нибудь енаме

кстати, почему енам не используем в проекте?

2024-05-18 14:19 UTC, neemkashu commented on src/shared/api/requests/loginUser.ts
> +  return undefined;
это по-умолчанию любая функция делает. если не прописан руками тип возвращаемого результата, то это избыточно

2024-05-18 14:19 UTC, neemkashu commented on src/shared/api/requests/signUpUser.ts
> +
```
  const countryShippingAbbr = countriesList.find(
    ({ name }) => name === shippingCountry,
  );
  const countryBillingAbbr = countriesList.find(
    ({ name }) => name === billingCountry,
  );
```

2024-05-18 14:19 UTC, neemkashu commented on src/shared/api/requests/signUpUser.ts
> +        ],
выглядит так, будто адресам лучше быть объектом с двумя полями: shipping и billing,  а не массивом из двух элементов

2024-05-18 14:19 UTC, neemkashu commented on src/shared/api/requests/signUpUser.ts
> +        billingAddresses: [1],
очень неявная логика, что это вообще такое? если это прям осмысленно, то надо вынести ноль и единицу в константы с именами, поясняющими что это

2024-05-18 14:19 UTC, neemkashu commented on src/shared/const/Countries.ts
> +export type CountryType = 'Belarus' | 'Russia' | 'Poland';
лучше завести енам

2024-05-18 14:19 UTC, neemkashu commented on src/shared/const/Countries.ts
> +export type CountryType = 'Belarus' | 'Russia' | 'Poland';
как минимум в форме регистрации эти страны вообще захардкожены строками оказались, легко такое потерять нафиг

optionValues={['Poland', 'Russia', 'Belarus']}

2024-05-18 14:19 UTC, neemkashu commented on src/shared/const/Validation.ts
> +  const currentCountry = countriesList.find((item) => item.name === country);
о, смотри, ты умеешь в find. вот и вместо самописного цикла в другом файле тоже надо. только добвть деструктурацию

2024-05-18 14:20 UTC, neemkashu commented on src/pages/MainPage/MainPage.tsx
> +            }}
делаем линки, а не кнопки

2024-05-18 14:21 UTC, samael-god commented on src/shared/api/requests/signUpUser.ts
> +        ],
это приколы commercetools, он именно в таком виде хочет их получать

2024-05-18 14:21 UTC, neemkashu commented on src/shared/api/requests/loginUser.ts
> +    (allTokens || !localStorage.getItem('refreshToken'))
найди все обращения к LS, где успел захардкодить строки в качестве ключей. детали в другом комменте

2024-05-18 14:21 UTC, samael-god commented on src/shared/api/requests/signUpUser.ts
> +        billingAddresses: [1],
тоже приколы КС, хочет указатели на массив адресов получить. но тут думаю можно придумать как более явно сделать

2024-05-18 14:22 UTC, neemkashu commented on src/shared/api/requests/loginUser.ts
> +function setLocalStorage(allTokens: boolean): void {
булевы перменные принято назвать с префиксом is /has

2024-05-18 14:26 UTC, neemkashu commented on src/shared/api/requests/signUpUser.ts
> +        billingAddresses: [1],
можно написать конвертер из данных, которыми вы в приложении пользуетесь, по-человески названными, в данные для КС и выделить это в отдельную функцию. есть шансы, что вам это  понадобится не только тут

2024-05-18 14:28 UTC, neemkashu commented on src/shared/api/requests/signUpUser.ts
> +        billingAddresses: [1],
> указатели на массив адресов получить

это точно так работает, проверяли уже? прсто это не указатели, а индексы, да ещё и в массив засунутые. на вам виднее :D

2024-05-18 14:45 UTC, Suficks commented on src/features/Login/ui/LoginForm.tsx
>      }
Исправила! Спасибо большое!

2024-05-18 14:47 UTC, Suficks commented on src/pages/MainPage/MainPage.tsx
> +        <img src={HeaderImage} alt="headerImage" className={cls.headerImage} />
Исправили)

2024-05-18 14:53 UTC, Suficks commented on src/shared/api/requests/loginUser.ts
> +      activeCartSignInMode: 'MergeWithExistingCustomerCart',
Исправлено

2024-05-18 14:54 UTC, Suficks commented on src/shared/api/BuildClient.ts
> +export let apirootPassword: ByProjectKeyRequestBuilder | null = null;
Убрали переменную

2024-05-18 14:54 UTC, Suficks commented on src/pages/MainPage/MainPage.tsx
> +                <img src={Icon_insta} alt="icon" />
Заменила на icon_facebook, icon_youtube и тд, норм?

2024-05-18 14:57 UTC, Suficks commented on src/shared/api/requests/loginUser.ts
> +    localStorage.setItem('token', tokenInstance.get().token);
Добавлен enum

2024-05-18 15:08 UTC, Suficks commented on src/shared/api/requests/signUpUser.ts
> +
Исправлено

2024-05-18 15:09 UTC, Suficks commented on src/shared/const/Validation.ts
> +  const currentCountry = countriesList.find((item) => item.name === country);
Сделано!

2024-05-18 15:56 UTC, NatashaKLe commented on src/pages/MainPage/MainPage.tsx
> +                }}
Сделано)

2024-05-18 15:57 UTC, NatashaKLe commented on src/pages/MainPage/MainPage.tsx
> +            }}
Сделано

2024-05-18 18:13 UTC, neemkashu commented on src/pages/MainPage/MainPage.tsx
> +                <img src={Icon_insta} alt="icon_insta" />
нет, это не очень удачный альт. смотри, это текст, который услышит человек, который пользуется скринридером. так что он услышит
 `icon underscore insta link` (линк сам скрин ридер добавит)
а должно быть что-то в духе
`our instagram link`

2024-05-18 18:13 UTC, neemkashu commented on src/shared/api/BuildClient.ts
> +    refreshToken: localStorage.getItem(LocalStorageKeys.REFRESH_TOKEN) || '',
🔥

2024-05-18 18:16 UTC, neemkashu commented on src/shared/api/requests/loginUser.ts
> +const mergeAnonymousCartWithCurrentUserCart = 'MergeWithExistingCustomerCart';
принято простые константы типа строк и чисел в таком стиле именовать

`const NAME_FOR_STRING_LOOKS_REALY_DIFFERENT_AND_OBVIOUS = 'string'`

2024-05-18 18:24 UTC, neemkashu commented on src/shared/api/requests/loginUser.ts
> +      LocalStorageKeys.VERSION,
радостно

кстати, вы знаеете, что JSON.stringify может выдать ошибку при попытке что-то превратить в строку, а у вас это теперь в catch ловится и вы можете не увидеть сообщение? можно рендерить что-то про интернал еррор и для себя месседж из ошибки тоже отображать

2024-05-18 19:30 UTC, NatashaKLe commented on src/pages/MainPage/MainPage.tsx
> +                <img src={Icon_insta} alt="icon_insta" />
Хорошо, поменяла на все иконки

2024-05-19 10:53 UTC, samael-god approved these changes

2024-05-19 13:03 UTC, merged